/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./EditStaffProfile.module.css";
import Sidebar from "./Sidebar";
import Header from "./Header";

const EditStaffProfile = () => {
  return (
    <div className={styles.editProfileContainer}>
      <Sidebar />
      <main className={styles.mainContent}>
        <Header title="Staff Main Menu" userName="Otor John" />
        <section className={styles.contentWrapper}>
          <button className={styles.backButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/92d04070e5253016cc4be210f7e39cd67ab13cb97ddace3a5754f5bb11e51fe4?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
              alt=""
              className={styles.backIcon}
            />
            Back
          </button>
          <div className={styles.formWrapper}>
            <h2 className={styles.formTitle}>Edit Staff Profile</h2>
            <form className={styles.editForm}>
              <div className={styles.formRow}>
                <div className={styles.formGroup}>
                  <label htmlFor="firstName" className={styles.formLabel}>
                    First name
                  </label>
                  <input
                    type="text"
                    id="firstName"
                    className={styles.formInput}
                    value="John"
                    readOnly
                  />
                </div>
                <div className={styles.formGroup}>
                  <label htmlFor="lastName" className={styles.formLabel}>
                    Last name
                  </label>
                  <input
                    type="text"
                    id="lastName"
                    className={styles.formInput}
                    value="Otor"
                    readOnly
                  />
                </div>
              </div>
              <div className={styles.formRow}>
                <div className={styles.formGroup}>
                  <label htmlFor="dob" className={styles.formLabel}>
                    DOB
                  </label>
                  <input
                    type="text"
                    id="dob"
                    className={styles.formInput}
                    value="July-15-1995"
                    readOnly
                  />
                </div>
                <div className={styles.formGroup}>
                  <label htmlFor="branchNumber" className={styles.formLabel}>
                    Branch number
                  </label>
                  <input
                    type="text"
                    id="branchNumber"
                    className={styles.formInput}
                    value="B026"
                    readOnly
                  />
                </div>
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="position" className={styles.formLabel}>
                  Position
                </label>
                <input
                  type="text"
                  id="position"
                  className={styles.formInput}
                  value="Agent"
                  readOnly
                />
              </div>
              <h3 className={styles.sectionTitle}>Updated Field</h3>
              <div className={styles.formGroup}>
                <label htmlFor="mobilePhone" className={styles.formLabel}>
                  Mobile phone
                </label>
                <input
                  type="tel"
                  id="mobilePhone"
                  className={styles.formInput}
                  value="647-123-4567"
                />
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="email" className={styles.formLabel}>
                  Email address
                </label>
                <input
                  type="email"
                  id="email"
                  className={styles.formInput}
                  value="johnotor@gmail.com"
                />
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="salary" className={styles.formLabel}>
                  Salary
                </label>
                <input
                  type="text"
                  id="salary"
                  className={styles.formInput}
                  value="6000"
                />
              </div>
              <button type="submit" className={styles.submitButton}>
                Submit
              </button>
            </form>
          </div>
        </section>
        <footer className={styles.footer}>
          Copyright © 2022 Relia Energy. All Rights Reserved
        </footer>
      </main>
    </div>
  );
};

export default EditStaffProfile;
