/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

const Header = ({ title, userName }) => {
  return (
    <header className={styles.header}>
      <h1 className={styles.title}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/56d0b045ff031fcc637c28fdd1e29823ca6184370839fe14c388738adc09374d?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
          alt=""
          className={styles.titleIcon}
        />
        {title}
      </h1>
      <div className={styles.userInfo}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/73dcd1195e1f8dd5b54e31c26501f67eb72453cbc217170ff7592a8e82dceabb?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
          alt=""
          className={styles.userIcon}
        />
        <span className={styles.userName}>{userName}</span>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/16558e49eb486ad7bc3941b88ab3068d7718a027ebb449f11aaa482ffc81feae?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
          alt=""
          className={styles.dropdownIcon}
        />
      </div>
    </header>
  );
};

export default Header;
