/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import StaffList from "./StaffList";
import StaffForm from "./StaffForm";
import EditStaffProfile from "./EditStaffProfile";
import SuccessModal from "./SuccessModal";

const StaffManagement = () => {
  const [currentView, setCurrentView] = useState("list");
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [successMessage, setSuccessMessage] = useState("");

  const handleAddStaff = () => {
    setCurrentView("form");
  };

  const handleEditStaff = () => {
    setCurrentView("edit");
  };

  const handleFormSubmit = (isNewStaff) => {
    setSuccessMessage(
      isNewStaff
        ? "You have successfully added a new staff"
        : "You have successfully updated profile of Otor John"
    );
    setShowSuccessModal(true);
  };

  const handleCloseModal = () => {
    setShowSuccessModal(false);
    setCurrentView("list");
  };

  return (
    <>
      {currentView === "list" && (
        <StaffList onAddStaff={handleAddStaff} onEditStaff={handleEditStaff} />
      )}
      {currentView === "form" && (
        <StaffForm onSubmit={() => handleFormSubmit(true)} />
      )}
      {currentView === "edit" && (
        <EditStaffProfile onSubmit={() => handleFormSubmit(false)} />
      )}
      {showSuccessModal && (
        <SuccessModal message={successMessage} onClose={handleCloseModal} />
      )}
    </>
  );
};

export default StaffManagement;
