/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SearchFilter.module.css";

const SearchFilter = ({ totalStaff }) => {
  return (
    <section className={styles.searchFilterContainer}>
      <div className={styles.searchWrapper}>
        <label htmlFor="staffSearch" className={styles.searchLabel}>
          Quick search a staff
        </label>
        <div className={styles.searchInputWrapper}>
          <input
            type="text"
            id="staffSearch"
            className={styles.searchInput}
            placeholder="Enter search word"
          />
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/70e4aae6b3ef7eefcc47451efa6a3fdcea3b06db43a27a49e35043d3f1d05ee7?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
            alt=""
            className={styles.searchIcon}
          />
        </div>
      </div>
      <div className={styles.totalStaff}>
        <span className={styles.totalNumber}>{totalStaff}</span>
        <span className={styles.totalLabel}>Total number of staff</span>
      </div>
      <div className={styles.filterWrapper}>
        <label htmlFor="staffFilter" className={styles.filterLabel}>
          Filter staff
        </label>
        <div className={styles.filterSelectWrapper}>
          <select id="staffFilter" className={styles.filterSelect}>
            <option>All staff</option>
          </select>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c31a07e1f963fc50666e0c88fe75f26b5a1f4bc3e205c7c27deff567500aec43?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
            alt=""
            className={styles.dropdownIcon}
          />
        </div>
      </div>
    </section>
  );
};

export default SearchFilter;
