/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Sidebar.module.css";

const Sidebar = () => {
  return (
    <aside className={styles.sidebar}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e3a5d649c5433e3a25670d36f1c4bf5956e9d40022c0c06c7a097a8ec1a4306?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
        alt="UiUxOtor Logo"
        className={styles.logo}
      />
      <h2 className={styles.systemName}>
        <span className={styles.bold}>UiUxOtor</span>
        <br />
        ERP System
      </h2>
      <nav className={styles.navigation}>
        <a href="#" className={styles.navItem}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a27c50a2f770858d7204598c441cfdb807943c18302e9848cc60d7fa88100d8e?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
            alt=""
            className={styles.navIcon}
          />
          <span>Dashboard</span>
        </a>
        <a href="#" className={styles.navItem}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d6c5b668adb55a6af2911ce4e9235c7854926c9d5f85bdd5c17b1deca04e4d9c?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
            alt=""
            className={styles.navIcon}
          />
          <span>Add New Staff</span>
        </a>
        <a href="#" className={`${styles.navItem} ${styles.active}`}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c5978703f760b7f6eff92ad59f1a8a8d1c332e3da3b7c554ef718b52889d1111?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
            alt=""
            className={styles.navIcon}
          />
          <span>List All Staffs</span>
        </a>
      </nav>
    </aside>
  );
};

export default Sidebar;
