/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./StaffList.module.css";
import Sidebar from "./Sidebar";
import Header from "./Header";
import SearchFilter from "./SearchFilter";
import StaffTable from "./StaffTable";
import Pagination from "./Pagination";

const StaffList = () => {
  return (
    <div className={styles.staffListContainer}>
      <Sidebar />
      <main className={styles.mainContent}>
        <Header title="Staff Main Menu" userName="Otor John" />
        <section className={styles.contentWrapper}>
          <SearchFilter totalStaff={250} />
          <StaffTable />
          <Pagination />
        </section>
        <footer className={styles.footer}>
          Copyright © 2022 Relia Energy. All Rights Reserved
        </footer>
      </main>
    </div>
  );
};

export default StaffList;
