/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./StaffForm.module.css";
import Sidebar from "./Sidebar";
import Header from "./Header";

const StaffForm = () => {
  return (
    <div className={styles.staffFormContainer}>
      <Sidebar />
      <main className={styles.mainContent}>
        <Header title="Staff Main Menu" userName="Otor John" />
        <section className={styles.formWrapper}>
          <h2 className={styles.formTitle}>Staff Hiring Form</h2>
          <form className={styles.staffForm}>
            <div className={styles.formRow}>
              <div className={styles.formGroup}>
                <label htmlFor="firstName" className={styles.formLabel}>
                  First name
                </label>
                <input
                  type="text"
                  id="firstName"
                  className={styles.formInput}
                  placeholder="Enter first name"
                />
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="lastName" className={styles.formLabel}>
                  Last name
                </label>
                <input
                  type="text"
                  id="lastName"
                  className={styles.formInput}
                  placeholder="Enter last name"
                />
              </div>
            </div>
            <div className={styles.formRow}>
              <div className={styles.formGroup}>
                <label htmlFor="dob" className={styles.formLabel}>
                  DOB
                </label>
                <div className={styles.inputWithIcon}>
                  <input
                    type="text"
                    id="dob"
                    className={styles.formInput}
                    placeholder="Enter date of birth"
                  />
                  <img
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/4f49f95d73c760666492b880ce6a5132f9299e2a9d4fd004ea74923a657a3bd2?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
                    alt=""
                    className={styles.inputIcon}
                  />
                </div>
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="email" className={styles.formLabel}>
                  Email address
                </label>
                <input
                  type="email"
                  id="email"
                  className={styles.formInput}
                  placeholder="Enter email address"
                />
              </div>
            </div>
            <div className={styles.formRow}>
              <div className={styles.formGroup}>
                <label htmlFor="branchNumber" className={styles.formLabel}>
                  Branch Number
                </label>
                <div className={styles.inputWithIcon}>
                  <select id="branchNumber" className={styles.formInput}>
                    <option value="">Select branch number</option>
                  </select>
                  <img
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/4f49f95d73c760666492b880ce6a5132f9299e2a9d4fd004ea74923a657a3bd2?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
                    alt=""
                    className={styles.inputIcon}
                  />
                </div>
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="mobilePhone" className={styles.formLabel}>
                  Mobile phone
                </label>
                <input
                  type="tel"
                  id="mobilePhone"
                  className={styles.formInput}
                  placeholder="Enter mobile phone"
                />
              </div>
            </div>
            <div className={styles.formRow}>
              <div className={styles.formGroup}>
                <label htmlFor="position" className={styles.formLabel}>
                  Position
                </label>
                <div className={styles.inputWithIcon}>
                  <select id="position" className={styles.formInput}>
                    <option value="">Select position</option>
                  </select>
                  <img
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/4f49f95d73c760666492b880ce6a5132f9299e2a9d4fd004ea74923a657a3bd2?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
                    alt=""
                    className={styles.inputIcon}
                  />
                </div>
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="salary" className={styles.formLabel}>
                  Salary
                </label>
                <input
                  type="text"
                  id="salary"
                  className={styles.formInput}
                  placeholder="Enter salary"
                />
              </div>
            </div>
            <div className={styles.formActions}>
              <button type="submit" className={styles.submitButton}>
                Add Staff
              </button>
              <button type="button" className={styles.cancelButton}>
                Cancel
              </button>
            </div>
          </form>
        </section>
        <footer className={styles.footer}>
          Copyright © 2022 Relia Energy. All Rights Reserved
        </footer>
      </main>
    </div>
  );
};

export default StaffForm;
