/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SuccessModal.module.css";

const SuccessModal = ({ message, onClose }) => {
  return (
    <div className={styles.modalOverlay}>
      <div className={styles.modalContent}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ab3c0ea231ae0c4e7d09a59b4de11fa6670c866b753f3cbfcaf220a12c5b393c?apiKey=2871edb3597c4b7a901bbf41bec8a8b2&"
          alt="Success"
          className={styles.successIcon}
        />
        <h2 className={styles.modalTitle}>Congratulations</h2>
        <p className={styles.modalMessage}>{message}</p>
        <button onClick={onClose} className={styles.closeButton}>
          Continue
        </button>
      </div>
    </div>
  );
};

export default SuccessModal;
